<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Coupon;
use Carbon\Carbon;

class CouponSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        Coupon::insert([

            // 1
            [
                'created_by_type' => 'admin',
                'created_by_id' => 1,
                'hospital_id' => null,
                'code' => 'WELCOME10',
                'title' => 'Welcome 10% Off',
                'description' => '10% discount for new customers.',
                'coupon_type' => 'coupon',
                'discount_type' => 'percentage',
                'discount_value' => 10,
                'max_discount' => 100,
                'min_order_amount' => 199,
                'applicable_to' => 'all',
                'new_customer_only' => 1,
                'first_appointment_only' => 0,
                'free_appointment' => 0,
                'usage_limit' => 1000,
                'usage_per_customer' => 1,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addMonths(3),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 2
            [
                'created_by_type' => 'admin',
                'created_by_id' => 1,
                'hospital_id' => null,
                'code' => 'WELCOME20',
                'title' => 'Welcome 20% Off',
                'description' => '20% discount for new customers.',
                'coupon_type' => 'coupon',
                'discount_type' => 'percentage',
                'discount_value' => 20,
                'max_discount' => 150,
                'min_order_amount' => 499,
                'applicable_to' => 'all',
                'new_customer_only' => 1,
                'first_appointment_only' => 0,
                'free_appointment' => 0,
                'usage_limit' => 500,
                'usage_per_customer' => 1,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addMonths(2),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 3
            [
                'created_by_type' => 'admin',
                'created_by_id' => 1,
                'hospital_id' => null,
                'code' => 'NEWUSER50',
                'title' => 'New User ₹50 Off',
                'description' => '₹50 discount for new customers.',
                'coupon_type' => 'coupon',
                'discount_type' => 'fixed',
                'discount_value' => 50,
                'max_discount' => null,
                'min_order_amount' => 299,
                'applicable_to' => 'all',
                'new_customer_only' => 1,
                'first_appointment_only' => 0,
                'free_appointment' => 0,
                'usage_limit' => 1000,
                'usage_per_customer' => 1,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addMonths(3),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 4
            [
                'created_by_type' => 'admin',
                'created_by_id' => 1,
                'hospital_id' => null,
                'code' => 'FIRSTAPT20',
                'title' => 'First Appointment 20% Off',
                'description' => '20% discount on first appointment.',
                'coupon_type' => 'offer',
                'discount_type' => 'percentage',
                'discount_value' => 20,
                'max_discount' => 200,
                'min_order_amount' => null,
                'applicable_to' => 'appointment',
                'new_customer_only' => 1,
                'first_appointment_only' => 1,
                'free_appointment' => 0,
                'usage_limit' => 500,
                'usage_per_customer' => 1,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addMonths(3),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 5
            [
                'created_by_type' => 'admin',
                'created_by_id' => 1,
                'hospital_id' => null,
                'code' => 'FREEAPT',
                'title' => 'Free First Appointment',
                'description' => 'Get your first doctor appointment free.',
                'coupon_type' => 'offer',
                'discount_type' => 'free',
                'discount_value' => 100,
                'max_discount' => null,
                'min_order_amount' => null,
                'applicable_to' => 'appointment',
                'new_customer_only' => 1,
                'first_appointment_only' => 1,
                'free_appointment' => 1,
                'usage_limit' => 100,
                'usage_per_customer' => 1,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addMonths(2),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 6
            [
                'created_by_type' => 'admin',
                'created_by_id' => 1,
                'hospital_id' => null,
                'code' => 'APT50',
                'title' => 'Appointment ₹50 Off',
                'description' => '₹50 discount on doctor appointments.',
                'coupon_type' => 'offer',
                'discount_type' => 'fixed',
                'discount_value' => 50,
                'max_discount' => null,
                'min_order_amount' => null,
                'applicable_to' => 'appointment',
                'new_customer_only' => 0,
                'first_appointment_only' => 0,
                'free_appointment' => 0,
                'usage_limit' => 1000,
                'usage_per_customer' => 2,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addMonths(3),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 7
            [
                'created_by_type' => 'admin',
                'created_by_id' => 1,
                'hospital_id' => null,
                'code' => 'APT10',
                'title' => 'Appointment 10% Off',
                'description' => '10% discount on appointments.',
                'coupon_type' => 'coupon',
                'discount_type' => 'percentage',
                'discount_value' => 10,
                'max_discount' => 100,
                'min_order_amount' => null,
                'applicable_to' => 'appointment',
                'new_customer_only' => 0,
                'first_appointment_only' => 0,
                'free_appointment' => 0,
                'usage_limit' => 1000,
                'usage_per_customer' => 3,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addMonths(3),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 8
            [
                'created_by_type' => 'admin',
                'created_by_id' => 1,
                'hospital_id' => null,
                'code' => 'APT100',
                'title' => 'Appointment ₹100 Off',
                'description' => '₹100 discount on appointments.',
                'coupon_type' => 'offer',
                'discount_type' => 'fixed',
                'discount_value' => 100,
                'max_discount' => null,
                'min_order_amount' => 500,
                'applicable_to' => 'appointment',
                'new_customer_only' => 0,
                'first_appointment_only' => 0,
                'free_appointment' => 0,
                'usage_limit' => 500,
                'usage_per_customer' => 1,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addMonths(2),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 9
            [
                'created_by_type' => 'admin',
                'created_by_id' => 1,
                'hospital_id' => null,
                'code' => 'MED10',
                'title' => 'Medicine 10% Off',
                'description' => '10% discount on medicine orders.',
                'coupon_type' => 'coupon',
                'discount_type' => 'percentage',
                'discount_value' => 10,
                'max_discount' => 150,
                'min_order_amount' => 300,
                'applicable_to' => 'medicine',
                'new_customer_only' => 0,
                'first_appointment_only' => 0,
                'free_appointment' => 0,
                'usage_limit' => 1000,
                'usage_per_customer' => 3,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addMonths(3),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 10
            [
                'created_by_type' => 'admin',
                'created_by_id' => 1,
                'hospital_id' => null,
                'code' => 'MED20',
                'title' => 'Medicine 20% Off',
                'description' => '20% discount on medicine orders.',
                'coupon_type' => 'coupon',
                'discount_type' => 'percentage',
                'discount_value' => 20,
                'max_discount' => 200,
                'min_order_amount' => 699,
                'applicable_to' => 'medicine',
                'new_customer_only' => 0,
                'first_appointment_only' => 0,
                'free_appointment' => 0,
                'usage_limit' => 500,
                'usage_per_customer' => 2,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addMonths(2),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 11
            [
                'created_by_type' => 'admin',
                'created_by_id' => 1,
                'hospital_id' => null,
                'code' => 'MED50',
                'title' => 'Medicine ₹50 Off',
                'description' => '₹50 discount on medicine orders.',
                'coupon_type' => 'coupon',
                'discount_type' => 'fixed',
                'discount_value' => 50,
                'max_discount' => null,
                'min_order_amount' => 299,
                'applicable_to' => 'medicine',
                'new_customer_only' => 0,
                'first_appointment_only' => 0,
                'free_appointment' => 0,
                'usage_limit' => 1000,
                'usage_per_customer' => 2,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addMonths(3),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 12
            [
                'created_by_type' => 'admin',
                'created_by_id' => 1,
                'hospital_id' => null,
                'code' => 'NEWMED100',
                'title' => 'New Customer Medicine ₹100 Off',
                'description' => '₹100 off on first medicine order.',
                'coupon_type' => 'coupon',
                'discount_type' => 'fixed',
                'discount_value' => 100,
                'max_discount' => null,
                'min_order_amount' => 599,
                'applicable_to' => 'medicine',
                'new_customer_only' => 1,
                'first_appointment_only' => 0,
                'free_appointment' => 0,
                'usage_limit' => 500,
                'usage_per_customer' => 1,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addMonths(2),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 13
            [
                'created_by_type' => 'admin',
                'created_by_id' => 1,
                'hospital_id' => null,
                'code' => 'HEALTH15',
                'title' => 'Healthcare 15% Off',
                'description' => '15% discount on eligible services.',
                'coupon_type' => 'coupon',
                'discount_type' => 'percentage',
                'discount_value' => 15,
                'max_discount' => 250,
                'min_order_amount' => 500,
                'applicable_to' => 'all',
                'new_customer_only' => 0,
                'first_appointment_only' => 0,
                'free_appointment' => 0,
                'usage_limit' => 2000,
                'usage_per_customer' => 2,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addMonths(3),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 14
            [
                'created_by_type' => 'admin',
                'created_by_id' => 1,
                'hospital_id' => null,
                'code' => 'HEALTH25',
                'title' => 'Healthcare ₹25 Off',
                'description' => '₹25 discount on eligible services.',
                'coupon_type' => 'coupon',
                'discount_type' => 'fixed',
                'discount_value' => 25,
                'max_discount' => null,
                'min_order_amount' => 199,
                'applicable_to' => 'all',
                'new_customer_only' => 0,
                'first_appointment_only' => 0,
                'free_appointment' => 0,
                'usage_limit' => 2000,
                'usage_per_customer' => 3,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addMonths(3),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 15
            [
                'created_by_type' => 'admin',
                'created_by_id' => 1,
                'hospital_id' => null,
                'code' => 'HEALTH30',
                'title' => 'Healthcare 30% Off',
                'description' => '30% discount on eligible services.',
                'coupon_type' => 'coupon',
                'discount_type' => 'percentage',
                'discount_value' => 30,
                'max_discount' => 300,
                'min_order_amount' => 999,
                'applicable_to' => 'all',
                'new_customer_only' => 0,
                'first_appointment_only' => 0,
                'free_appointment' => 0,
                'usage_limit' => 300,
                'usage_per_customer' => 1,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addMonth(),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 16
            [
                'created_by_type' => 'hospital',
                'created_by_id' => 1,
                'hospital_id' => 1,
                'code' => 'HOSPITAL50',
                'title' => 'Hospital ₹50 Off',
                'description' => '₹50 off at selected hospital.',
                'coupon_type' => 'offer',
                'discount_type' => 'fixed',
                'discount_value' => 50,
                'max_discount' => null,
                'min_order_amount' => 300,
                'applicable_to' => 'appointment',
                'new_customer_only' => 0,
                'first_appointment_only' => 0,
                'free_appointment' => 0,
                'usage_limit' => 500,
                'usage_per_customer' => 2,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addMonths(2),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 17
            [
                'created_by_type' => 'hospital',
                'created_by_id' => 1,
                'hospital_id' => 1,
                'code' => 'HOSPITAL10',
                'title' => 'Hospital 10% Off',
                'description' => '10% off on appointments at selected hospital.',
                'coupon_type' => 'offer',
                'discount_type' => 'percentage',
                'discount_value' => 10,
                'max_discount' => 100,
                'min_order_amount' => null,
                'applicable_to' => 'appointment',
                'new_customer_only' => 0,
                'first_appointment_only' => 0,
                'free_appointment' => 0,
                'usage_limit' => 500,
                'usage_per_customer' => 2,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addMonths(2),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 18
            [
                'created_by_type' => 'hospital',
                'created_by_id' => 1,
                'hospital_id' => 1,
                'code' => 'HOSPFREE',
                'title' => 'Hospital Free Appointment',
                'description' => 'Free first appointment at selected hospital.',
                'coupon_type' => 'offer',
                'discount_type' => 'free',
                'discount_value' => 100,
                'max_discount' => null,
                'min_order_amount' => null,
                'applicable_to' => 'appointment',
                'new_customer_only' => 1,
                'first_appointment_only' => 1,
                'free_appointment' => 1,
                'usage_limit' => 100,
                'usage_per_customer' => 1,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addMonths(2),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 19
            [
                'created_by_type' => 'hospital',
                'created_by_id' => 1,
                'hospital_id' => 1,
                'code' => 'HOSPMED20',
                'title' => 'Hospital Medicine 20% Off',
                'description' => '20% discount on medicines from selected hospital.',
                'coupon_type' => 'coupon',
                'discount_type' => 'percentage',
                'discount_value' => 20,
                'max_discount' => 200,
                'min_order_amount' => 500,
                'applicable_to' => 'medicine',
                'new_customer_only' => 0,
                'first_appointment_only' => 0,
                'free_appointment' => 0,
                'usage_limit' => 300,
                'usage_per_customer' => 2,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addMonths(2),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 20
            [
                'created_by_type' => 'hospital',
                'created_by_id' => 1,
                'hospital_id' => 1,
                'code' => 'HOSPMED100',
                'title' => 'Hospital Medicine ₹100 Off',
                'description' => '₹100 discount on medicine orders.',
                'coupon_type' => 'coupon',
                'discount_type' => 'fixed',
                'discount_value' => 100,
                'max_discount' => null,
                'min_order_amount' => 799,
                'applicable_to' => 'medicine',
                'new_customer_only' => 0,
                'first_appointment_only' => 0,
                'free_appointment' => 0,
                'usage_limit' => 300,
                'usage_per_customer' => 1,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addMonths(2),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 21
            [
                'created_by_type' => 'admin',
                'created_by_id' => 1,
                'hospital_id' => null,
                'code' => 'SAVE75',
                'title' => 'Save ₹75',
                'description' => '₹75 discount on eligible orders.',
                'coupon_type' => 'coupon',
                'discount_type' => 'fixed',
                'discount_value' => 75,
                'max_discount' => null,
                'min_order_amount' => 499,
                'applicable_to' => 'all',
                'new_customer_only' => 0,
                'first_appointment_only' => 0,
                'free_appointment' => 0,
                'usage_limit' => 1000,
                'usage_per_customer' => 2,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addMonths(3),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 22
            [
                'created_by_type' => 'admin',
                'created_by_id' => 1,
                'hospital_id' => null,
                'code' => 'SAVE200',
                'title' => 'Save ₹200',
                'description' => '₹200 discount on eligible orders.',
                'coupon_type' => 'coupon',
                'discount_type' => 'fixed',
                'discount_value' => 200,
                'max_discount' => null,
                'min_order_amount' => 1499,
                'applicable_to' => 'all',
                'new_customer_only' => 0,
                'first_appointment_only' => 0,
                'free_appointment' => 0,
                'usage_limit' => 500,
                'usage_per_customer' => 1,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addMonths(2),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 23
            [
                'created_by_type' => 'admin',
                'created_by_id' => 1,
                'hospital_id' => null,
                'code' => 'CARE5',
                'title' => 'Healthcare 5% Off',
                'description' => '5% discount on eligible services.',
                'coupon_type' => 'coupon',
                'discount_type' => 'percentage',
                'discount_value' => 5,
                'max_discount' => 50,
                'min_order_amount' => 199,
                'applicable_to' => 'all',
                'new_customer_only' => 0,
                'first_appointment_only' => 0,
                'free_appointment' => 0,
                'usage_limit' => 3000,
                'usage_per_customer' => 5,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addMonths(4),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 24
            [
                'created_by_type' => 'admin',
                'created_by_id' => 1,
                'hospital_id' => null,
                'code' => 'WEEKEND15',
                'title' => 'Weekend 15% Off',
                'description' => '15% discount on eligible services.',
                'coupon_type' => 'offer',
                'discount_type' => 'percentage',
                'discount_value' => 15,
                'max_discount' => 150,
                'min_order_amount' => 399,
                'applicable_to' => 'all',
                'new_customer_only' => 0,
                'first_appointment_only' => 0,
                'free_appointment' => 0,
                'usage_limit' => 1000,
                'usage_per_customer' => 1,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addDays(30),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 25
            [
                'created_by_type' => 'admin',
                'created_by_id' => 1,
                'hospital_id' => null,
                'code' => 'FAMILY100',
                'title' => 'Family Healthcare ₹100 Off',
                'description' => '₹100 discount for family healthcare services.',
                'coupon_type' => 'offer',
                'discount_type' => 'fixed',
                'discount_value' => 100,
                'max_discount' => null,
                'min_order_amount' => 799,
                'applicable_to' => 'all',
                'new_customer_only' => 0,
                'first_appointment_only' => 0,
                'free_appointment' => 0,
                'usage_limit' => 500,
                'usage_per_customer' => 2,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addMonths(2),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 26
            [
                'created_by_type' => 'admin',
                'created_by_id' => 1,
                'hospital_id' => null,
                'code' => 'FIRSTMED15',
                'title' => 'First Medicine Order 15% Off',
                'description' => '15% discount on first medicine order.',
                'coupon_type' => 'coupon',
                'discount_type' => 'percentage',
                'discount_value' => 15,
                'max_discount' => 150,
                'min_order_amount' => 399,
                'applicable_to' => 'medicine',
                'new_customer_only' => 1,
                'first_appointment_only' => 0,
                'free_appointment' => 0,
                'usage_limit' => 500,
                'usage_per_customer' => 1,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addMonths(2),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 27
            [
                'created_by_type' => 'admin',
                'created_by_id' => 1,
                'hospital_id' => null,
                'code' => 'FIRSTAPT50',
                'title' => 'First Appointment ₹50 Off',
                'description' => '₹50 discount on first appointment.',
                'coupon_type' => 'offer',
                'discount_type' => 'fixed',
                'discount_value' => 50,
                'max_discount' => null,
                'min_order_amount' => null,
                'applicable_to' => 'appointment',
                'new_customer_only' => 1,
                'first_appointment_only' => 1,
                'free_appointment' => 0,
                'usage_limit' => 1000,
                'usage_per_customer' => 1,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addMonths(3),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 28
            [
                'created_by_type' => 'admin',
                'created_by_id' => 1,
                'hospital_id' => null,
                'code' => 'DOCTOR25',
                'title' => 'Doctor Consultation ₹25 Off',
                'description' => '₹25 discount on doctor consultation.',
                'coupon_type' => 'offer',
                'discount_type' => 'fixed',
                'discount_value' => 25,
                'max_discount' => null,
                'min_order_amount' => null,
                'applicable_to' => 'appointment',
                'new_customer_only' => 0,
                'first_appointment_only' => 0,
                'free_appointment' => 0,
                'usage_limit' => 2000,
                'usage_per_customer' => 3,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addMonths(3),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 29
            [
                'created_by_type' => 'admin',
                'created_by_id' => 1,
                'hospital_id' => null,
                'code' => 'UPCOMING50',
                'title' => 'Upcoming ₹50 Offer',
                'description' => 'Special offer coming soon.',
                'coupon_type' => 'offer',
                'discount_type' => 'fixed',
                'discount_value' => 50,
                'max_discount' => null,
                'min_order_amount' => 299,
                'applicable_to' => 'all',
                'new_customer_only' => 0,
                'first_appointment_only' => 0,
                'free_appointment' => 0,
                'usage_limit' => 500,
                'usage_per_customer' => 1,
                'used_count' => 0,
                'starts_at' => $now->copy()->addDays(5),
                'expires_at' => $now->copy()->addMonths(2),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 30
            [
                'created_by_type' => 'admin',
                'created_by_id' => 1,
                'hospital_id' => null,
                'code' => 'HEALTH500',
                'title' => 'Healthcare ₹500 Off',
                'description' => '₹500 discount on high value eligible orders.',
                'coupon_type' => 'coupon',
                'discount_type' => 'fixed',
                'discount_value' => 500,
                'max_discount' => null,
                'min_order_amount' => 2999,
                'applicable_to' => 'all',
                'new_customer_only' => 0,
                'first_appointment_only' => 0,
                'free_appointment' => 0,
                'usage_limit' => 200,
                'usage_per_customer' => 1,
                'used_count' => 0,
                'starts_at' => $now,
                'expires_at' => $now->copy()->addMonths(2),
                'status' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}